eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

microservice:
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/make-order
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/do-payment
        uri2: http://PAYMENT-SERVICE/payment/get-payment
